package neu.edu.entity;
// Generated Dec 14, 2017 2:47:12 AM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseRecord generated by hbm2java
 */
@Entity
@Table(name = "purchase_record", catalog = "finalprj")
public class PurchaseRecord implements java.io.Serializable {

	private Integer purchaseRecordId;
	private IdeaOption ideaOption;
	private User user;
	private float purchaseRecordAmount;
	private Date purchaseRecordDate;
	private String purchaseRecordStatus;

	public PurchaseRecord() {
	}

	public PurchaseRecord(IdeaOption ideaOption, User user, float purchaseRecordAmount, Date purchaseRecordDate,
			String purchaseRecordStatus) {
		this.ideaOption = ideaOption;
		this.user = user;
		this.purchaseRecordAmount = purchaseRecordAmount;
		this.purchaseRecordDate = purchaseRecordDate;
		this.purchaseRecordStatus = purchaseRecordStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "purchase_record_id", unique = true, nullable = false)
	public Integer getPurchaseRecordId() {
		return this.purchaseRecordId;
	}

	public void setPurchaseRecordId(Integer purchaseRecordId) {
		this.purchaseRecordId = purchaseRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "option_id", nullable = false)
	public IdeaOption getIdeaOption() {
		return this.ideaOption;
	}

	public void setIdeaOption(IdeaOption ideaOption) {
		this.ideaOption = ideaOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "purchase_record_amount", nullable = false, precision = 12, scale = 0)
	public float getPurchaseRecordAmount() {
		return this.purchaseRecordAmount;
	}

	public void setPurchaseRecordAmount(float purchaseRecordAmount) {
		this.purchaseRecordAmount = purchaseRecordAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_record_date", nullable = false, length = 19)
	public Date getPurchaseRecordDate() {
		return this.purchaseRecordDate;
	}

	public void setPurchaseRecordDate(Date purchaseRecordDate) {
		this.purchaseRecordDate = purchaseRecordDate;
	}

	@Column(name = "purchase_record_status", nullable = false, length = 20)
	public String getPurchaseRecordStatus() {
		return this.purchaseRecordStatus;
	}

	public void setPurchaseRecordStatus(String purchaseRecordStatus) {
		this.purchaseRecordStatus = purchaseRecordStatus;
	}

}
