package neu.edu.entity;
// Generated Dec 14, 2017 2:47:12 AM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Startup generated by hbm2java
 */
@Entity
@Table(name = "startup", catalog = "finalprj")
public class Startup implements java.io.Serializable {

	private Integer startupId;
	private Category category;
	private User user;
	private String startupName;
	private String startupDescription;

	public Startup() {
	}

	public Startup(Category category, User user) {
		this.category = category;
		this.user = user;
	}

	public Startup(Category category, User user, String startupName, String startupDescription) {
		this.category = category;
		this.user = user;
		this.startupName = startupName;
		this.startupDescription = startupDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "startup_id", unique = true, nullable = false)
	public Integer getStartupId() {
		return this.startupId;
	}

	public void setStartupId(Integer startupId) {
		this.startupId = startupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "startup_name", length = 100)
	public String getStartupName() {
		return this.startupName;
	}

	public void setStartupName(String startupName) {
		this.startupName = startupName;
	}

	@Column(name = "startup_description", length = 4000)
	public String getStartupDescription() {
		return this.startupDescription;
	}

	public void setStartupDescription(String startupDescription) {
		this.startupDescription = startupDescription;
	}

}
